name: cimilo_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  weather: ^2.0.1
  google_fonts: ^2.2.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

 
  uses-material-design: true

  assets:
    - image/bg.jpeg


